// tslint:disable
/**
 * Airbyte Configuration API
 * Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@airbyte.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    DbMigrationExecutionRead,
    DbMigrationExecutionReadFromJSON,
    DbMigrationExecutionReadToJSON,
    DbMigrationReadList,
    DbMigrationReadListFromJSON,
    DbMigrationReadListToJSON,
    DbMigrationRequestBody,
    DbMigrationRequestBodyFromJSON,
    DbMigrationRequestBodyToJSON,
    InvalidInputExceptionInfo,
    InvalidInputExceptionInfoFromJSON,
    InvalidInputExceptionInfoToJSON,
    NotFoundKnownExceptionInfo,
    NotFoundKnownExceptionInfoFromJSON,
    NotFoundKnownExceptionInfoToJSON,
} from '../models';

export interface ExecuteMigrationsRequest {
    dbMigrationRequestBody: DbMigrationRequestBody;
}

export interface ListMigrationsRequest {
    dbMigrationRequestBody: DbMigrationRequestBody;
}


/**
 * Migrate the database to the latest version
 */
function executeMigrationsRaw<T>(requestParameters: ExecuteMigrationsRequest, requestConfig: runtime.TypedQueryConfig<T, DbMigrationExecutionRead> = {}): QueryConfig<T> {
    if (requestParameters.dbMigrationRequestBody === null || requestParameters.dbMigrationRequestBody === undefined) {
        throw new runtime.RequiredError('dbMigrationRequestBody','Required parameter requestParameters.dbMigrationRequestBody was null or undefined when calling executeMigrations.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/db_migrations/migrate`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || DbMigrationRequestBodyToJSON(requestParameters.dbMigrationRequestBody),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(DbMigrationExecutionReadFromJSON(body), text);
    }

    return config;
}

/**
* Migrate the database to the latest version
*/
export function executeMigrations<T>(requestParameters: ExecuteMigrationsRequest, requestConfig?: runtime.TypedQueryConfig<T, DbMigrationExecutionRead>): QueryConfig<T> {
    return executeMigrationsRaw(requestParameters, requestConfig);
}

/**
 * List all database migrations
 */
function listMigrationsRaw<T>(requestParameters: ListMigrationsRequest, requestConfig: runtime.TypedQueryConfig<T, DbMigrationReadList> = {}): QueryConfig<T> {
    if (requestParameters.dbMigrationRequestBody === null || requestParameters.dbMigrationRequestBody === undefined) {
        throw new runtime.RequiredError('dbMigrationRequestBody','Required parameter requestParameters.dbMigrationRequestBody was null or undefined when calling listMigrations.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/db_migrations/list`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || DbMigrationRequestBodyToJSON(requestParameters.dbMigrationRequestBody),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(DbMigrationReadListFromJSON(body), text);
    }

    return config;
}

/**
* List all database migrations
*/
export function listMigrations<T>(requestParameters: ListMigrationsRequest, requestConfig?: runtime.TypedQueryConfig<T, DbMigrationReadList>): QueryConfig<T> {
    return listMigrationsRaw(requestParameters, requestConfig);
}

