// tslint:disable
/**
 * Airbyte Configuration API
 * Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@airbyte.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    InvalidInputExceptionInfo,
    InvalidInputExceptionInfoFromJSON,
    InvalidInputExceptionInfoToJSON,
    JobDebugInfoRead,
    JobDebugInfoReadFromJSON,
    JobDebugInfoReadToJSON,
    JobIdRequestBody,
    JobIdRequestBodyFromJSON,
    JobIdRequestBodyToJSON,
    JobInfoRead,
    JobInfoReadFromJSON,
    JobInfoReadToJSON,
    JobListRequestBody,
    JobListRequestBodyFromJSON,
    JobListRequestBodyToJSON,
    JobReadList,
    JobReadListFromJSON,
    JobReadListToJSON,
    NotFoundKnownExceptionInfo,
    NotFoundKnownExceptionInfoFromJSON,
    NotFoundKnownExceptionInfoToJSON,
} from '../models';

export interface CancelJobRequest {
    jobIdRequestBody: JobIdRequestBody;
}

export interface GetJobDebugInfoRequest {
    jobIdRequestBody: JobIdRequestBody;
}

export interface GetJobInfoRequest {
    jobIdRequestBody: JobIdRequestBody;
}

export interface ListJobsForRequest {
    jobListRequestBody: JobListRequestBody;
}


/**
 * Cancels a job
 */
function cancelJobRaw<T>(requestParameters: CancelJobRequest, requestConfig: runtime.TypedQueryConfig<T, JobInfoRead> = {}): QueryConfig<T> {
    if (requestParameters.jobIdRequestBody === null || requestParameters.jobIdRequestBody === undefined) {
        throw new runtime.RequiredError('jobIdRequestBody','Required parameter requestParameters.jobIdRequestBody was null or undefined when calling cancelJob.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/jobs/cancel`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || JobIdRequestBodyToJSON(requestParameters.jobIdRequestBody),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(JobInfoReadFromJSON(body), text);
    }

    return config;
}

/**
* Cancels a job
*/
export function cancelJob<T>(requestParameters: CancelJobRequest, requestConfig?: runtime.TypedQueryConfig<T, JobInfoRead>): QueryConfig<T> {
    return cancelJobRaw(requestParameters, requestConfig);
}

/**
 * Gets all information needed to debug this job
 */
function getJobDebugInfoRaw<T>(requestParameters: GetJobDebugInfoRequest, requestConfig: runtime.TypedQueryConfig<T, JobDebugInfoRead> = {}): QueryConfig<T> {
    if (requestParameters.jobIdRequestBody === null || requestParameters.jobIdRequestBody === undefined) {
        throw new runtime.RequiredError('jobIdRequestBody','Required parameter requestParameters.jobIdRequestBody was null or undefined when calling getJobDebugInfo.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/jobs/get_debug_info`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || JobIdRequestBodyToJSON(requestParameters.jobIdRequestBody),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(JobDebugInfoReadFromJSON(body), text);
    }

    return config;
}

/**
* Gets all information needed to debug this job
*/
export function getJobDebugInfo<T>(requestParameters: GetJobDebugInfoRequest, requestConfig?: runtime.TypedQueryConfig<T, JobDebugInfoRead>): QueryConfig<T> {
    return getJobDebugInfoRaw(requestParameters, requestConfig);
}

/**
 * Get information about a job
 */
function getJobInfoRaw<T>(requestParameters: GetJobInfoRequest, requestConfig: runtime.TypedQueryConfig<T, JobInfoRead> = {}): QueryConfig<T> {
    if (requestParameters.jobIdRequestBody === null || requestParameters.jobIdRequestBody === undefined) {
        throw new runtime.RequiredError('jobIdRequestBody','Required parameter requestParameters.jobIdRequestBody was null or undefined when calling getJobInfo.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/jobs/get`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || JobIdRequestBodyToJSON(requestParameters.jobIdRequestBody),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(JobInfoReadFromJSON(body), text);
    }

    return config;
}

/**
* Get information about a job
*/
export function getJobInfo<T>(requestParameters: GetJobInfoRequest, requestConfig?: runtime.TypedQueryConfig<T, JobInfoRead>): QueryConfig<T> {
    return getJobInfoRaw(requestParameters, requestConfig);
}

/**
 * Returns recent jobs for a connection. Jobs are returned in descending order by createdAt.
 */
function listJobsForRaw<T>(requestParameters: ListJobsForRequest, requestConfig: runtime.TypedQueryConfig<T, JobReadList> = {}): QueryConfig<T> {
    if (requestParameters.jobListRequestBody === null || requestParameters.jobListRequestBody === undefined) {
        throw new runtime.RequiredError('jobListRequestBody','Required parameter requestParameters.jobListRequestBody was null or undefined when calling listJobsFor.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/jobs/list`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || JobListRequestBodyToJSON(requestParameters.jobListRequestBody),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(JobReadListFromJSON(body), text);
    }

    return config;
}

/**
* Returns recent jobs for a connection. Jobs are returned in descending order by createdAt.
*/
export function listJobsFor<T>(requestParameters: ListJobsForRequest, requestConfig?: runtime.TypedQueryConfig<T, JobReadList>): QueryConfig<T> {
    return listJobsForRaw(requestParameters, requestConfig);
}

