// tslint:disable
/**
 * Airbyte Configuration API
 * Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@airbyte.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    CheckConnectionRead,
    CheckConnectionReadFromJSON,
    CheckConnectionReadToJSON,
    DestinationCoreConfig,
    DestinationCoreConfigFromJSON,
    DestinationCoreConfigToJSON,
    InvalidInputExceptionInfo,
    InvalidInputExceptionInfoFromJSON,
    InvalidInputExceptionInfoToJSON,
    SourceCoreConfig,
    SourceCoreConfigFromJSON,
    SourceCoreConfigToJSON,
    SourceDiscoverSchemaRead,
    SourceDiscoverSchemaReadFromJSON,
    SourceDiscoverSchemaReadToJSON,
} from '../models';

export interface ExecuteDestinationCheckConnectionRequest {
    destinationCoreConfig: DestinationCoreConfig;
}

export interface ExecuteSourceCheckConnectionRequest {
    sourceCoreConfig: SourceCoreConfig;
}

export interface ExecuteSourceDiscoverSchemaRequest {
    sourceCoreConfig: SourceCoreConfig;
}


/**
 * Run check connection for a given destination configuration
 */
function executeDestinationCheckConnectionRaw<T>(requestParameters: ExecuteDestinationCheckConnectionRequest, requestConfig: runtime.TypedQueryConfig<T, CheckConnectionRead> = {}): QueryConfig<T> {
    if (requestParameters.destinationCoreConfig === null || requestParameters.destinationCoreConfig === undefined) {
        throw new runtime.RequiredError('destinationCoreConfig','Required parameter requestParameters.destinationCoreConfig was null or undefined when calling executeDestinationCheckConnection.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/scheduler/destinations/check_connection`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || DestinationCoreConfigToJSON(requestParameters.destinationCoreConfig),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(CheckConnectionReadFromJSON(body), text);
    }

    return config;
}

/**
* Run check connection for a given destination configuration
*/
export function executeDestinationCheckConnection<T>(requestParameters: ExecuteDestinationCheckConnectionRequest, requestConfig?: runtime.TypedQueryConfig<T, CheckConnectionRead>): QueryConfig<T> {
    return executeDestinationCheckConnectionRaw(requestParameters, requestConfig);
}

/**
 * Run check connection for a given source configuration
 */
function executeSourceCheckConnectionRaw<T>(requestParameters: ExecuteSourceCheckConnectionRequest, requestConfig: runtime.TypedQueryConfig<T, CheckConnectionRead> = {}): QueryConfig<T> {
    if (requestParameters.sourceCoreConfig === null || requestParameters.sourceCoreConfig === undefined) {
        throw new runtime.RequiredError('sourceCoreConfig','Required parameter requestParameters.sourceCoreConfig was null or undefined when calling executeSourceCheckConnection.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/scheduler/sources/check_connection`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || SourceCoreConfigToJSON(requestParameters.sourceCoreConfig),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(CheckConnectionReadFromJSON(body), text);
    }

    return config;
}

/**
* Run check connection for a given source configuration
*/
export function executeSourceCheckConnection<T>(requestParameters: ExecuteSourceCheckConnectionRequest, requestConfig?: runtime.TypedQueryConfig<T, CheckConnectionRead>): QueryConfig<T> {
    return executeSourceCheckConnectionRaw(requestParameters, requestConfig);
}

/**
 * Run discover schema for a given source a source configuration
 */
function executeSourceDiscoverSchemaRaw<T>(requestParameters: ExecuteSourceDiscoverSchemaRequest, requestConfig: runtime.TypedQueryConfig<T, SourceDiscoverSchemaRead> = {}): QueryConfig<T> {
    if (requestParameters.sourceCoreConfig === null || requestParameters.sourceCoreConfig === undefined) {
        throw new runtime.RequiredError('sourceCoreConfig','Required parameter requestParameters.sourceCoreConfig was null or undefined when calling executeSourceDiscoverSchema.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/v1/scheduler/sources/discover_schema`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || SourceCoreConfigToJSON(requestParameters.sourceCoreConfig),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(SourceDiscoverSchemaReadFromJSON(body), text);
    }

    return config;
}

/**
* Run discover schema for a given source a source configuration
*/
export function executeSourceDiscoverSchema<T>(requestParameters: ExecuteSourceDiscoverSchemaRequest, requestConfig?: runtime.TypedQueryConfig<T, SourceDiscoverSchemaRead>): QueryConfig<T> {
    return executeSourceDiscoverSchemaRaw(requestParameters, requestConfig);
}

