/* tslint:disable */
/* eslint-disable */
/**
 * Airbyte Configuration API
 * Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@airbyte.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConnectionStateType,
    ConnectionStateTypeFromJSON,
    ConnectionStateTypeFromJSONTyped,
    ConnectionStateTypeToJSON,
} from './ConnectionStateType';
import {
    GlobalState,
    GlobalStateFromJSON,
    GlobalStateFromJSONTyped,
    GlobalStateToJSON,
} from './GlobalState';
import {
    StreamState,
    StreamStateFromJSON,
    StreamStateFromJSONTyped,
    StreamStateToJSON,
} from './StreamState';

/**
 * Contains the state for a connection. The stateType field identifies what type of state it is. Only the field corresponding to that type will be set, the rest will be null. If stateType=not_set, then none of the fields will be set.
 * @export
 * @interface ConnectionState
 */
export interface ConnectionState {
    /**
     * 
     * @type {ConnectionStateType}
     * @memberof ConnectionState
     */
    stateType: ConnectionStateType;
    /**
     * 
     * @type {string}
     * @memberof ConnectionState
     */
    connectionId: string;
    /**
     * 
     * @type {object}
     * @memberof ConnectionState
     */
    state?: object;
    /**
     * 
     * @type {Array<StreamState>}
     * @memberof ConnectionState
     */
    streamState?: Array<StreamState>;
    /**
     * 
     * @type {GlobalState}
     * @memberof ConnectionState
     */
    globalState?: GlobalState;
}

export function ConnectionStateFromJSON(json: any): ConnectionState {
    return ConnectionStateFromJSONTyped(json, false);
}

export function ConnectionStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stateType': ConnectionStateTypeFromJSON(json['stateType']),
        'connectionId': json['connectionId'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'streamState': !exists(json, 'streamState') ? undefined : ((json['streamState'] as Array<any>).map(StreamStateFromJSON)),
        'globalState': !exists(json, 'globalState') ? undefined : GlobalStateFromJSON(json['globalState']),
    };
}

export function ConnectionStateToJSON(value?: ConnectionState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stateType': ConnectionStateTypeToJSON(value.stateType),
        'connectionId': value.connectionId,
        'state': value.state,
        'streamState': value.streamState === undefined ? undefined : ((value.streamState as Array<any>).map(StreamStateToJSON)),
        'globalState': GlobalStateToJSON(value.globalState),
    };
}

